### ISSUE TITLE
📈 Add rule and sample app around clean testing best practices

### ISSUE THREAD

**Issue by danielmackay** [SSWConsulting/SSW.SAW.General#16]
Currently with integration testing we are using both Respawn and Test Containers to create and reset our databases.

```[tasklist]
### Tasks
- [ ] Create a rule that provides guidance on when to use respawn vs a new test container
- [ ] The rule should take performance into account
- [ ] Create a sample repo to demonstrate the approach
- [ ] Add the sample repo to the awesome-ca repo
```
